pipeline:
  name: flash-templates
  identifier: flashtemplates
  projectIdentifier: W_Inc
  orgIdentifier: SE_Sandbox
  tags: {}
  stages:
    - stage:
        name: geneva
        identifier: geneva
        description: ""
        type: CI
        spec:
          cloneCodebase: false
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Node Build
                  identifier: Node_Build
                  spec:
                    shell: Sh
                    command: node app.js
